create table if not exists public.web_vitals_events (
  id bigint generated by default as identity primary key,
  schema_version smallint not null default 1,
  metric_name text not null check (metric_name in ('CLS', 'FCP', 'INP', 'LCP', 'TTFB')),
  metric_id text not null,
  metric_value double precision not null check (metric_value >= 0),
  metric_delta double precision not null check (metric_delta >= 0),
  rating text not null check (rating in ('good', 'needs-improvement', 'poor')),
  route_key text not null,
  route_path text not null,
  page_type text not null,
  captured_at timestamptz not null,
  received_at timestamptz not null default timezone('utc', now()),
  app_version text not null,
  environment text not null,
  device_class text not null,
  viewport_bucket text not null,
  network_type text,
  save_data boolean,
  referrer_category text not null,
  navigation_type text not null,
  was_restored_from_bfcache boolean not null default false,
  sample_rate double precision not null default 1 check (sample_rate > 0 and sample_rate <= 1),
  constraint web_vitals_events_metric_id_key unique (metric_name, metric_id)
);

create index if not exists web_vitals_events_received_at_idx
  on public.web_vitals_events (received_at desc);

create index if not exists web_vitals_events_metric_received_at_idx
  on public.web_vitals_events (metric_name, received_at desc);

create index if not exists web_vitals_events_route_metric_received_at_idx
  on public.web_vitals_events (route_key, metric_name, received_at desc);

create index if not exists web_vitals_events_app_version_received_at_idx
  on public.web_vitals_events (app_version, received_at desc);

create or replace function public.classify_web_vital(
  metric_name_input text,
  metric_value_input double precision
)
returns text
language sql
immutable
set search_path = public
as $$
  select case metric_name_input
    when 'LCP' then
      case
        when metric_value_input <= 2500 then 'good'
        when metric_value_input <= 4000 then 'needs-improvement'
        else 'poor'
      end
    when 'INP' then
      case
        when metric_value_input <= 200 then 'good'
        when metric_value_input <= 500 then 'needs-improvement'
        else 'poor'
      end
    when 'CLS' then
      case
        when metric_value_input <= 0.1 then 'good'
        when metric_value_input <= 0.25 then 'needs-improvement'
        else 'poor'
      end
    when 'FCP' then
      case
        when metric_value_input <= 1800 then 'good'
        when metric_value_input <= 3000 then 'needs-improvement'
        else 'poor'
      end
    when 'TTFB' then
      case
        when metric_value_input <= 800 then 'good'
        when metric_value_input <= 1800 then 'needs-improvement'
        else 'poor'
      end
    else 'poor'
  end;
$$;

create or replace function public.get_web_vitals_overview(
  window_days integer default 7,
  environment_filter text default 'production',
  release_filter text default null
)
returns table (
  metric_name text,
  p75_value double precision,
  rating text,
  sample_count bigint,
  good_count bigint,
  needs_improvement_count bigint,
  poor_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with scoped as (
    select
      event.metric_name,
      event.metric_value,
      event.rating
    from public.web_vitals_events event
    where public.is_admin_aal2(array['admin']::text[])
      and event.received_at >= timezone('utc', now()) - make_interval(days => greatest(window_days, 1))
      and (environment_filter is null or event.environment = environment_filter)
      and (release_filter is null or event.app_version = release_filter)
  ),
  aggregated as (
    select
      scoped.metric_name,
      percentile_cont(0.75) within group (order by scoped.metric_value) as p75_value,
      count(*)::bigint as sample_count,
      count(*) filter (where scoped.rating = 'good')::bigint as good_count,
      count(*) filter (where scoped.rating = 'needs-improvement')::bigint as needs_improvement_count,
      count(*) filter (where scoped.rating = 'poor')::bigint as poor_count
    from scoped
    group by scoped.metric_name
  )
  select
    aggregated.metric_name,
    aggregated.p75_value,
    public.classify_web_vital(aggregated.metric_name, aggregated.p75_value) as rating,
    aggregated.sample_count,
    aggregated.good_count,
    aggregated.needs_improvement_count,
    aggregated.poor_count
  from aggregated
  order by array_position(array['LCP', 'INP', 'CLS', 'FCP', 'TTFB']::text[], aggregated.metric_name);
$$;

create or replace function public.get_web_vitals_route_summary(
  window_days integer default 7,
  environment_filter text default 'production',
  release_filter text default null,
  limit_count integer default 5
)
returns table (
  metric_name text,
  route_key text,
  page_type text,
  p75_value double precision,
  rating text,
  sample_count bigint,
  poor_count bigint,
  poor_rate double precision
)
language sql
stable
security definer
set search_path = public
as $$
  with scoped as (
    select
      event.metric_name,
      event.route_key,
      event.page_type,
      event.metric_value,
      event.rating
    from public.web_vitals_events event
    where public.is_admin_aal2(array['admin']::text[])
      and event.received_at >= timezone('utc', now()) - make_interval(days => greatest(window_days, 1))
      and (environment_filter is null or event.environment = environment_filter)
      and (release_filter is null or event.app_version = release_filter)
  ),
  aggregated as (
    select
      scoped.metric_name,
      scoped.route_key,
      min(scoped.page_type) as page_type,
      percentile_cont(0.75) within group (order by scoped.metric_value) as p75_value,
      count(*)::bigint as sample_count,
      count(*) filter (where scoped.rating = 'poor')::bigint as poor_count
    from scoped
    group by scoped.metric_name, scoped.route_key
    having count(*) >= 5
  ),
  ranked as (
    select
      aggregated.*,
      row_number() over (
        partition by aggregated.metric_name
        order by aggregated.p75_value desc, aggregated.sample_count desc, aggregated.route_key
      ) as route_rank
    from aggregated
  )
  select
    ranked.metric_name,
    ranked.route_key,
    ranked.page_type,
    ranked.p75_value,
    public.classify_web_vital(ranked.metric_name, ranked.p75_value) as rating,
    ranked.sample_count,
    ranked.poor_count,
    round(((ranked.poor_count::numeric / nullif(ranked.sample_count, 0)::numeric) * 100), 1)::double precision as poor_rate
  from ranked
  where ranked.route_rank <= greatest(limit_count, 1)
  order by array_position(array['LCP', 'INP', 'CLS', 'FCP', 'TTFB']::text[], ranked.metric_name), ranked.route_rank;
$$;

create or replace function public.get_web_vitals_daily_trends(
  window_days integer default 14,
  environment_filter text default 'production',
  release_filter text default null
)
returns table (
  bucket_date date,
  metric_name text,
  p75_value double precision,
  rating text,
  sample_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with scoped as (
    select
      timezone('utc', event.received_at)::date as bucket_date,
      event.metric_name,
      event.metric_value
    from public.web_vitals_events event
    where public.is_admin_aal2(array['admin']::text[])
      and event.received_at >= timezone('utc', now()) - make_interval(days => greatest(window_days, 1))
      and (environment_filter is null or event.environment = environment_filter)
      and (release_filter is null or event.app_version = release_filter)
  ),
  aggregated as (
    select
      scoped.bucket_date,
      scoped.metric_name,
      percentile_cont(0.75) within group (order by scoped.metric_value) as p75_value,
      count(*)::bigint as sample_count
    from scoped
    group by scoped.bucket_date, scoped.metric_name
  )
  select
    aggregated.bucket_date,
    aggregated.metric_name,
    aggregated.p75_value,
    public.classify_web_vital(aggregated.metric_name, aggregated.p75_value) as rating,
    aggregated.sample_count
  from aggregated
  order by aggregated.bucket_date asc, array_position(array['LCP', 'INP', 'CLS', 'FCP', 'TTFB']::text[], aggregated.metric_name);
$$;

create or replace function public.get_web_vitals_device_summary(
  window_days integer default 14,
  environment_filter text default 'production',
  release_filter text default null
)
returns table (
  metric_name text,
  device_class text,
  p75_value double precision,
  rating text,
  sample_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with scoped as (
    select
      event.metric_name,
      event.device_class,
      event.metric_value
    from public.web_vitals_events event
    where public.is_admin_aal2(array['admin']::text[])
      and event.received_at >= timezone('utc', now()) - make_interval(days => greatest(window_days, 1))
      and (environment_filter is null or event.environment = environment_filter)
      and (release_filter is null or event.app_version = release_filter)
  ),
  aggregated as (
    select
      scoped.metric_name,
      scoped.device_class,
      percentile_cont(0.75) within group (order by scoped.metric_value) as p75_value,
      count(*)::bigint as sample_count
    from scoped
    group by scoped.metric_name, scoped.device_class
  )
  select
    aggregated.metric_name,
    aggregated.device_class,
    aggregated.p75_value,
    public.classify_web_vital(aggregated.metric_name, aggregated.p75_value) as rating,
    aggregated.sample_count
  from aggregated
  order by array_position(array['LCP', 'INP', 'CLS', 'FCP', 'TTFB']::text[], aggregated.metric_name), aggregated.device_class;
$$;

create or replace function public.get_web_vitals_release_summary(
  window_days integer default 30,
  environment_filter text default 'production',
  release_limit integer default 5
)
returns table (
  app_version text,
  metric_name text,
  p75_value double precision,
  rating text,
  sample_count bigint,
  last_received_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  with recent_releases as (
    select
      event.app_version,
      max(event.received_at) as last_received_at
    from public.web_vitals_events event
    where public.is_admin_aal2(array['admin']::text[])
      and event.received_at >= timezone('utc', now()) - make_interval(days => greatest(window_days, 1))
      and (environment_filter is null or event.environment = environment_filter)
    group by event.app_version
    order by last_received_at desc
    limit greatest(release_limit, 1)
  ),
  scoped as (
    select
      event.app_version,
      event.metric_name,
      event.metric_value,
      release.last_received_at
    from public.web_vitals_events event
    join recent_releases release on release.app_version = event.app_version
    where (environment_filter is null or event.environment = environment_filter)
  ),
  aggregated as (
    select
      scoped.app_version,
      scoped.metric_name,
      scoped.last_received_at,
      percentile_cont(0.75) within group (order by scoped.metric_value) as p75_value,
      count(*)::bigint as sample_count
    from scoped
    group by scoped.app_version, scoped.metric_name, scoped.last_received_at
  )
  select
    aggregated.app_version,
    aggregated.metric_name,
    aggregated.p75_value,
    public.classify_web_vital(aggregated.metric_name, aggregated.p75_value) as rating,
    aggregated.sample_count,
    aggregated.last_received_at
  from aggregated
  order by aggregated.last_received_at desc, array_position(array['LCP', 'INP', 'CLS', 'FCP', 'TTFB']::text[], aggregated.metric_name);
$$;

alter table public.web_vitals_events enable row level security;

drop policy if exists "web_vitals_events_admin_read" on public.web_vitals_events;
create policy "web_vitals_events_admin_read"
on public.web_vitals_events
for select
to authenticated
using (public.is_admin_aal2(array['admin']::text[]));

grant select on public.web_vitals_events to authenticated;

revoke execute on function public.get_web_vitals_overview(integer, text, text) from public;
revoke execute on function public.get_web_vitals_route_summary(integer, text, text, integer) from public;
revoke execute on function public.get_web_vitals_daily_trends(integer, text, text) from public;
revoke execute on function public.get_web_vitals_device_summary(integer, text, text) from public;
revoke execute on function public.get_web_vitals_release_summary(integer, text, integer) from public;

grant execute on function public.get_web_vitals_overview(integer, text, text) to authenticated;
grant execute on function public.get_web_vitals_route_summary(integer, text, text, integer) to authenticated;
grant execute on function public.get_web_vitals_daily_trends(integer, text, text) to authenticated;
grant execute on function public.get_web_vitals_device_summary(integer, text, text) to authenticated;
grant execute on function public.get_web_vitals_release_summary(integer, text, integer) to authenticated;
